-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 21:16:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laravel
-- ------C-----------------------------------------------
DROP SCHEMA IF EXISTS `laravel` ;

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `laravel`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `guard_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `permissions_name_guard_name_unique` (`name` ASC, `guard_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`model_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`model_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `model_id`, `model_type`),
  INDEX `model_has_permissions_model_id_model_type_index` (`model_id` ASC, `model_type` ASC) VISIBLE,
  CONSTRAINT `model_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `laravel`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `guard_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_guard_name_unique` (`name` ASC, `guard_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`model_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`model_has_roles` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `model_id`, `model_type`),
  INDEX `model_has_roles_model_id_model_type_index` (`model_id` ASC, `model_type` ASC) VISIBLE,
  CONSTRAINT `model_has_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `laravel`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`personal_access_tokens` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`role_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `role_has_permissions_role_id_foreign` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `laravel`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `laravel`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `laravel`.` Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.` Perfil` (
  `id Perfil` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(25) NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `creat_at` TIMESTAMP NULL,
  `Update_at` TIMESTAMP NULL,
  ` Perfilcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id Perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`DLVGuardado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`DLVGuardado` (
  `idDLVGuardado` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NULL,
  `update_at` TIMESTAMP NULL,
  `create_at` TIMESTAMP NULL,
  `DLVGuardadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idDLVGuardado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`CLINGOGuardado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`CLINGOGuardado` (
  `id_clingo` INT NOT NULL AUTO_INCREMENT,
  `contenido TEXT` VARCHAR(45) NULL,
  `CLINGOGuardadocol` VARCHAR(45) NULL,
  `create_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  `CLINGOGuardadocol1` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clingo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  ` Perfil_id Perfil` INT NOT NULL,
  `DLVGuardado_idDLVGuardado` INT NOT NULL,
  `CLINGOGuardado_id_clingo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE,
  INDEX `fk_users_ Perfil1_idx` (` Perfil_id Perfil` ASC) VISIBLE,
  INDEX `fk_users_DLVGuardado1_idx` (`DLVGuardado_idDLVGuardado` ASC) VISIBLE,
  INDEX `fk_users_CLINGOGuardado1_idx` (`CLINGOGuardado_id_clingo` ASC) VISIBLE,
  CONSTRAINT `fk_users_ Perfil1`
    FOREIGN KEY (` Perfil_id Perfil`)
    REFERENCES `laravel`.` Perfil` (`id Perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_DLVGuardado1`
    FOREIGN KEY (`DLVGuardado_idDLVGuardado`)
    REFERENCES `laravel`.`DLVGuardado` (`idDLVGuardado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_CLINGOGuardado1`
    FOREIGN KEY (`CLINGOGuardado_id_clingo`)
    REFERENCES `laravel`.`CLINGOGuardado` (`id_clingo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `laravel`.` Info_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.` Info_Usuario` (
  `id Info_Usuario` INT NOT NULL AUTO_INCREMENT,
  ` Fecha_nacimiento` DATETIME NULL,
  `sexo` VARCHAR(10) NULL,
  `created_at` TIMESTAMP NULL,
  ` Info_Usuariocol` VARCHAR(45) NULL,
  ` Info_Usuariocol1` VARCHAR(45) NULL,
  `Update_at` TIMESTAMP NOT NULL,
  ` Info_Usuariocol2` VARCHAR(45) NULL,
  PRIMARY KEY (`id Info_Usuario`, `Update_at`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
